<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="Sachin-Sharma" ignored="1" name="Default test(failed)" tests="1" failures="1" timestamp="05 Jan 2023 13:44:22 GMT" time="0.121" errors="0">
  <testcase name="test2" time="0.024" classname="com.qa.retryconcept.TestNgRetryDemo">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at com.qa.retryconcept.TestNgRetryDemo.test2(TestNgRetryDemo.java:16)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- test2 -->
  <testcase name="test1" time="0.0" classname="com.qa.retryconcept.TestNgRetryDemo">
    <ignored/>
  </testcase> <!-- test1 -->
</testsuite> <!-- Default test(failed) -->
